name: ci
run-name: ${{ github.actor }} is building python unit tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
         python-version: '3.9'
         
      - name: Install packages
      - run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Run python tests
      - run: |
            pytest